djangobb_forum/urls.py
from django.conf.urls import url

from djangobb_forum import settings as forum_settings
from djangobb_forum import views as forum_views
from djangobb_forum.feeds import LastPosts, LastTopics, LastPostsOnForum, \
     LastPostsOnCategory, LastPostsOnTopic
from djangobb_forum.forms import EssentialsProfileForm, \
    PersonalProfileForm, MessagingProfileForm, PersonalityProfileForm, \
    DisplayProfileForm, PrivacyProfileForm, UploadAvatarForm


urlpatterns = [

    # Forum
    url('^$', forum_views.index, name='index'),
    url('^(?P<forum_id>\d+)/$', forum_views.show_forum, name='forum'),
    url('^moderate/(?P<forum_id>\d+)/$', forum_views.moderate, name='moderate'),
    url('^search/$', forum_views.search, name='search'),
    url('^misc/$', forum_views.misc, name='misc'),

    # User
    url('^user/(?P<username>.*)/upload_avatar/$', forum_views.upload_avatar, {
        'form_class': UploadAvatarForm,
        'template': 'djangobb_forum/upload_avatar.html'
        }, name='forum_profile_upload_avatar'),
    url('^user/(?P<username>.*)/privacy/$', forum_views.user, {
        'section': 'privacy',
        'form_class': PrivacyProfileForm,
        'template': 'djangobb_forum/profile/profile_privacy.html'
        }, name='forum_profile_privacy'),
    url('^user/(?P<username>.*)/display/$', forum_views.user, {
        'section': 'display',
        'form_class': DisplayProfileForm,
        'template': 'djangobb_forum/profile/profile_display.html'
        }, name='forum_profile_display'),
    url('^user/(?P<username>.*)/personality/$', forum_views.user, {
        'section': 'personality',
        'form_class': PersonalityProfileForm,
        'template': 'djangobb_forum/profile/profile_personality.html'
        }, name='forum_profile_personality'),
    url('^user/(?P<username>.*)/messaging/$', forum_views.user, {
        'section': 'messaging',
        'form_class': MessagingProfileForm,
        'template': 'djangobb_forum/profile/profile_messaging.html'
        }, name='forum_profile_messaging'),
    url('^user/(?P<username>.*)/personal/$', forum_views.user, {
        'section': 'personal',
        'form_class': PersonalProfileForm,
        'template': 'djangobb_forum/profile/profile_personal.html'
        }, name='forum_profile_personal'),
    url('^user/(?P<username>.*)/essentials/$', forum_views.user, name='forum_profile_essentials'),
    url('^user/(?P<username>.*)/$', forum_views.user, name='forum_profile'),
    url('^users/$', forum_views.users, name='forum_users'),

    # Topic
    url('^topic/(?P<topic_id>\d+)/$', forum_views.show_topic, name='topic'),
    url('^(?P<forum_id>\d+)/topic/add/$', forum_views.add_topic, name='add_topic'),
    url('^topic/(?P<topic_id>\d+)/delete_posts/$', forum_views.delete_posts, name='delete_posts'),
    url('^topic/move/$', forum_views.move_topic, name='move_topic'),
    url('^topic/(?P<topic_id>\d+)/stick_unstick/(?P<action>[s|u])/$', forum_views.stick_unstick_topic, name='stick_unstick_topic'),
    url('^topic/(?P<topic_id>\d+)/open_close/(?P<action>[c|o])/$', forum_views.open_close_topic, name='open_close_topic'),

    # Post
    url('^post/(?P<post_id>\d+)/$', forum_views.show_post, name='post'),
    url('^post/(?P<post_id>\d+)/edit/$', forum_views.edit_post, name='edit_post'),
    url('^post/(?P<post_id>\d+)/delete/$', forum_views.delete_post, name='delete_post'),
    # Post preview
    url(r'^preview/$', forum_views.post_preview, name='post_preview'),

    # Subscription
    url('^subscription/topic/(?P<topic_id>\d+)/delete/$', forum_views.delete_subscription, name='forum_delete_subscription'),
    url('^subscription/topic/(?P<topic_id>\d+)/add/$', forum_views.add_subscription, name='forum_add_subscription'),

    # Feeds
    url(r'^feeds/posts/$', LastPosts(), name='forum_posts_feed'),
    url(r'^feeds/topics/$', LastTopics(), name='forum_topics_feed'),
    url(r'^feeds/topic/(?P<topic_id>\d+)/$', LastPostsOnTopic(), name='forum_topic_feed'),
    url(r'^feeds/forum/(?P<forum_id>\d+)/$', LastPostsOnForum(), name='forum_forum_feed'),
    url(r'^feeds/category/(?P<category_id>\d+)/$', LastPostsOnCategory(), name='forum_category_feed'),
]

### EXTENSIONS ###

# LOFI Extension
if (forum_settings.LOFI_SUPPORT):
    urlpatterns += [
        url('^lofi/$', forum_views.index, {'full':False}, name='lofi_index'),
        url('^(?P<forum_id>\d+)/lofi/$', forum_views.show_forum, {'full':False}, name='lofi_forum'),
        url('^topic/(?P<topic_id>\d+)/lofi/$', forum_views.show_topic, {'full':False}, name='lofi_topic'),
    ]

# REPUTATION Extension
if (forum_settings.REPUTATION_SUPPORT):
    urlpatterns += [
        url('^reputation/(?P<username>.*)/$', forum_views.reputation, name='reputation'),
    ]

# ATTACHMENT Extension
if (forum_settings.ATTACHMENT_SUPPORT):
    urlpatterns += [
        url('^attachment/(?P<hash>\w+)/$', forum_views.show_attachment, name='forum_attachment'),
    ]

main/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import RedirectView
from django.core.urlresolvers import reverse_lazy
from django.conf import settings
from django.conf.urls.static import static

from users import views as users_views
from blogs import views as blogs_views
from cms import views as cms_views
from main import views as main_views


urlpatterns = [
    url(r'^$', blogs_views.IndexView.as_view(), name='index'),

    url(r'^poslednie-statyi/$', blogs_views.PostChoicesListView.as_view(is_last=True), name='posts-last-list'),
    url(r'^popularnye-statyi/$', blogs_views.PostChoicesListView.as_view(is_populate=True), name='posts-popular-list'),
    url(r'^kommentiruemye-statyi/$', blogs_views.PostChoicesListView.as_view(is_commented=True), name='posts-commented-list'),
    url(r'^poisk/$', blogs_views.PostSearchListView.as_view(), name='posts-search'),
    url(r'^kontakty/$', cms_views.FeedbackCreateView.as_view(), name='feedback'),
    url(r'^reklamodatelyam/$', cms_views.FlatPageDetailView.as_view(), name='advertisers'),
    url(r'^pravila-i-avtorskie-prava/$', cms_views.FlatPageDetailView.as_view(), name='rules'),

    url(r'^posts/$', blogs_views.PostListView.as_view(), name='posts-list'),
    url(r'^posts/(?P<slug>[-_\w]+)/$', blogs_views.PostCategoryDetailView.as_view(), name='posts-category-detail'),
    url(r'^category/(?P<category_slug>[-_\w]+)/$', blogs_views.PostCategoryListView.as_view(), name='posts-category-list'),
    
    url(r'^u/login/$', users_views.LoginView.as_view(), name='u-login'),
    url(r'^u/logout/$', users_views.LogoutView.as_view(), name='u-logout'),
    url(r'^u/registration/$', users_views.RegistrationView.as_view(), name='u-registration'),
    url(r'^u/registration/(?P<uuid>.*)/$', users_views.RegistrationUuidView.as_view(), name='u-registration-uuid'),
    url(r'^u/reset/password/$', users_views.PasswordResetView.as_view(), name='u-reset-password'),
    url(r'^u/reset/password/(?P<uuid>.*)/$', users_views.PasswordResetUuidView.as_view(), name='u-reset-password-uuid'),
    url(r'^u/profile/(?P<pk>\d+)/$', users_views.UserDetailView.as_view(), name='u-profile'),
    url(r'^u/update/(?P<pk>\d+)/$', users_views.UserUpdateView.as_view(), name='u-update'),
    url(r'^u/password/$', users_views.PasswordChangeView.as_view(), name='u-password'),
    url(r'^u/subscribe/$', users_views.SubscribeUser.as_view(), name='subscribe-user'),
    
    url(r'^u/comments/$', blogs_views.CommentUserListView.as_view(), name='u-comments-list'),
    url(r'^json/comment/$', blogs_views.comment_json, name='json-comment'),
    url(r'^json/comment/like/$', blogs_views.comment_like, name='json-comment-like'),
    url(r'^json/comment/unlike/$', blogs_views.comment_unlike, name='json-comment-unlike'),
    url(r'^json/post/like/$', blogs_views.post_like, name='json-post-like'),
    url(r'^json/post/unlike/$', blogs_views.post_unlike, name='json-post-unlike'),
    url(r'^json/cms/vote/$', cms_views.cms_vote, name='json-cms-vote'),

    url(r'^u/flush/$', main_views.flush_cache),
    url(r'^u/admin/', include(admin.site.urls)),
    url(r'^u/ckeditor/upload/', main_views.ImageUploadView.as_view(), name='ckeditor_upload'),
    url(r'^u/ckeditor/', include('ckeditor_uploader.urls')),

    url(r'^robots\.txt$', main_views.RobotTemplateView.as_view()),
    url(r'^sitemap\.xml$', main_views.sitemap_xml),
    url(r'^sitemap-(?P<section>.+)\.xml$', main_views.sitemap_xml),
    url(r'^sitemap\.html$', main_views.sitemap_html, name='sitemap-html'),
    url(r'^feed\.rss$', main_views.feed, name='feed'),

    url(r'^m/$', RedirectView.as_view(url=reverse_lazy('index'))),
    url(r'^mobile/$', RedirectView.as_view(url=reverse_lazy('index'))),
    url(r'^posts/tag/(?P<tag_slug>[-_\w]+)/$', RedirectView.as_view(url=reverse_lazy('index'))),
    url(r'^karta-sajta\.html$', RedirectView.as_view(url=reverse_lazy('sitemap-html'))),
    url(r'^favicon\.ico$', RedirectView.as_view(url='/static/favicon.ico')),
    
    url(r'^forum/', include('djangobb_forum.urls', namespace='djangobb'))
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/views.py
#-*- encoding: utf-8 -*-
import uuid

from django.shortcuts import redirect
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse_lazy, reverse
from django.utils.translation import ugettext_lazy as _ul, ugettext as _u
from django.views.generic import FormView, RedirectView, CreateView, UpdateView, ListView, DetailView
from django.contrib.auth import logout, login
from django.db.models import Q
from django.http import Http404
from django.contrib import messages
from django.conf import settings
from django.core.mail import send_mail
from django.utils import timezone

from main.mixins import MessageMixin
from users.forms import LoginForm, RegistrationForm, PasswordChangeForm, UserForm, SubscribeForm, PasswordResetForm
from users.models import User


class LoginView(MessageMixin, FormView):
    template_name = 'login.html'
    form_class = LoginForm

    def get_success_url(self):
        next_url = self.request.GET.get('next', None)
        if next_url is not None:
            return next_url
        return reverse_lazy('index')

    def form_valid(self, form):
        email = form.cleaned_data['email']
        user = form.cleaned_data['user']
        if user is not None:
            login(self.request, user)
        return super(LoginView, self).form_valid(form)


class LogoutView(RedirectView):
    url = reverse_lazy('index')

    def get_redirect_url(self):
        logout(self.request)
        next_url = self.request.GET.get('next', None)
        if next_url is not None:
            return next_url
        return super(LogoutView, self).get_redirect_url()

    @method_decorator(login_required(login_url=reverse_lazy('u-login')))
    def dispatch(self, *args, **kwargs):
        return super(LogoutView, self).dispatch(*args, **kwargs)


class RegistrationView(MessageMixin, FormView):
    template_name = 'registration.html'
    form_class = RegistrationForm
    success_url = reverse_lazy('u-login')
    success_msg = _ul(u'Ссылка для окончания регистрации отправлена Вам на почту (если письмо не пришло поищите его в спаме).')

    def send_registration(self, user, key):
        registration_url = 'http://obelektrike.ru' + reverse('u-registration-uuid', kwargs={'uuid': key})
        message = _ul(u"""
            Для окончания регистрации перейдите по следующей ссылке:\n
            %s \n
            \n
            С уважением,
            Команда obelektrike.ru
            """) % registration_url
        send_mail(
            subject=_ul(u'Регистрация пользователя на сайте obelektrike.ru'),
            message=message,
            from_email=settings.SUPPORT_EMAIL,
            recipient_list=[user.email],
            fail_silently=True
            )

    def form_valid(self, form):
        key = uuid.uuid4()
        user = User.objects.create(
            username=form.cleaned_data['email'],
            registration_key=key,
            is_active=False,
            )
        user.set_password(form.cleaned_data['password'])
        user.save()
        self.send_registration(user, key)
        return super(RegistrationView, self).form_valid(form)


class RegistrationUuidView(RedirectView):
    url = reverse_lazy('index')

    def get_redirect_url(self, *args, **kwargs):
        try:
            self.user = User.objects.get(registration_key=kwargs['uuid'])
        except User.DoesNotExist:
            raise Http404
        self.user.is_active = True
        self.user.registration_key = None
        self.user.save()
        return super(RegistrationUuidView, self).get_redirect_url()


class PasswordResetView(MessageMixin, FormView):
    template_name = 'password-reset.html'
    form_class = PasswordResetForm
    success_url = reverse_lazy('u-reset-password')
    success_msg = _ul(u'Ссылка для сброса пароля отправлена Вам на почту (если письмо не пришло поищите его в спаме).')

    def send_resetpassword(self, user, key):
        reset_url = 'http://obelektrike.ru' + reverse('u-reset-password-uuid', kwargs={'uuid': key})
        message = _ul(u"""
            Для сброса пароль перейдите по следующей ссылке:\n
            %s \n
            \n
            С уважением,
            Команда obelektrike.ru
            """) % reset_url
        send_mail(
            subject=_ul(u'Сброс пароля для пользователя %s на obelektrike.ru') % user.get_full_name(),
            message=message,
            from_email=settings.SUPPORT_EMAIL,
            recipient_list=[user.email],
            fail_silently=True
            )

    def form_valid(self, form):
        key = uuid.uuid4()
        user = User.objects.get(username=form.cleaned_data['email'])
        user.reset_password_key = key
        user.save()
        self.send_resetpassword(user, key)
        return super(PasswordResetView, self).form_valid(form)


class PasswordResetUuidView(MessageMixin, FormView):
    template_name = 'password.html'
    form_class = PasswordChangeForm
    success_url = reverse_lazy('u-login')
    success_msg = _ul(u'Пароль успешно изменен. Зайдите используя новый пароль.')

    def form_valid(self, form):
        self.user.set_password(form.cleaned_data['password'])
        self.user.reset_password_key = None
        self.user.save()
        return super(PasswordResetUuidView, self).form_valid(form)

    def dispatch(self, *args, **kwargs):
        try:
            self.user = User.objects.get(reset_password_key=self.kwargs['uuid'])
        except User.DoesNotExist:
            raise Http404
        return super(PasswordResetUuidView, self).dispatch(*args, **kwargs)


class PasswordChangeView(MessageMixin, FormView):
    template_name = 'password.html'
    form_class = PasswordChangeForm
    success_url = reverse_lazy('index')

    def form_valid(self, form):
        self.request.user.set_password(form.cleaned_data['password'])
        self.request.user.save()
        return super(PasswordChangeView, self).form_valid(form)

    @method_decorator(login_required(login_url=reverse_lazy('u-login')))
    def dispatch(self, *args, **kwargs):
        return super(PasswordChangeView, self).dispatch(*args, **kwargs)


class UserUpdateView(MessageMixin, UpdateView):
    template_name = 'user-update.html'
    form_class = UserForm
    model = User

    def get_object(self, queryset=None):
        obj = super(UserUpdateView, self).get_object(queryset=queryset)
        if self.request.user.is_staff or self.request.user.pk == obj.pk:
            return obj
        raise Http404

    def get_success_url(self):
        return reverse_lazy('u-profile', kwargs={'pk': self.object.pk})

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(UserUpdateView, self).dispatch(*args, **kwargs)


class UserDetailView(DetailView):
    template_name = 'user.html'
    model = User


class SubscribeUser(MessageMixin, FormView):
    template_name = ''
    form_class = SubscribeForm
    extra_tags = 'subscribe'
    success_msg = _ul(u'Теперь уведомление о каждой новой статьи будет приходить Вам на email.')

    def get(self, request, *args, **kwargs):
        raise Http404

    def get_success_url(self):
        next_url = self.request.GET.get('next', None)
        if next_url is not None:
            return next_url
        return reverse_lazy('index')

    def form_valid(self, form):
        user, _ = User.objects.get_or_create(
            username=form.cleaned_data['email'],
            defaults=dict(
                email=form.cleaned_data['email'],
                is_active=False
                )
            )
        user.is_subscribe = True
        user.date_subscribe = timezone.now()
        user.save()
        return super(SubscribeUser, self).form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, form.errors.as_text(), extra_tags=self.extra_tags)
        return redirect(self.get_success_url())

djangobb_forum/templates/djangobb_forum/add_topic.html
{% extends 'djangobb_forum/base.html' %}
{% load forum_extras %}
{% load i18n %}

{% block content %}
<div class="linkst">
	<div class="inbox">
		{% if forum %}
		<ul class="start"><li><a href="{% url 'djangobb:index' %}">{% trans "Root" %}</a> </li><li>&raquo; {% link forum %}</li></ul>
		{% else %}
			<ul><li><a href="{% url 'djangobb:index' %}">{% trans "Root" %}</a> </li><li>&raquo; {% link topic.forum %}</li><li>&raquo; {{ topic }}</li></ul>
		{% endif %}
		<div class="clearer"></div>
	</div>
</div>
{% include "djangobb_forum/includes/post_form.html" %}
{% endblock %}

djangobb_forum/templates/djangobb_forum/base.html
{% load forum_extras %}
{% load i18n %}
{% load staticfiles %}


<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<title>{% block title %}{% endblock %} {{ forum_settings.FORUM_BASE_TITLE }}</title>
	<meta name="description" content="{{ forum_settings.FORUM_META_DESCRIPTION }} " />
	<meta name="keywords" content="{{ forum_settings.FORUM_META_KEYWORDS }}" />
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />

	<link rel="stylesheet" type="text/css" href="{% static 'djangobb_forum/themes/obelektrike/style.css' %}" />

	<link rel="alternate" type="application/atom+xml" href="{% url 'djangobb:forum_posts_feed' %}" title="{% trans "Latest posts on forum" %}" />
	<link rel="alternate" type="application/atom+xml" href="{% url 'djangobb:forum_topics_feed' %}" title="{% trans "Latest topics on forum" %}" />

	<link rel="shortcut icon" href="{% static 'favicon.ico' %}" type="image/x-icon" alt="об электрике">
	<script type="text/javascript">
		var STATIC_URL = "/static/";
		var POST_PREVIEW_URL = "{% url 'djangobb:post_preview' %}";
	</script>
	{% if DEBUG %}
	   <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.2.0/jquery.js"></script>
	{% else %}
    	<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.2.0/jquery.min.js" ></script>
	{% endif %}
	{% if user.is_authenticated %}
    	{% if post %}
            {% with markup=post.markup %}
                {% include "djangobb_forum/includes/markup_editor.html" %}
            {% endwith %}
        {% else %}
            {% with markup=user.forum_profile.markup %}
                {% include "djangobb_forum/includes/markup_editor.html" %}
            {% endwith %}
        {% endif %}
    	<script type="text/javascript">
    	   $(document).ready(function() {
    		$(".markup").markItUp(mySettings);
    	   });
    	</script>
	{% endif %}

    <!-- Highlightjs goodies -->
	<link type="text/css" rel="stylesheet" href="{% static 'djangobb_forum/css/pygments.css' %}" />
	{% if highlight_word %}
		<script type="text/javascript" src="{% static 'djangobb_forum/js/jquery.highlight-3.pack.js' %}"></script>
		<script type="text/javascript">
			$(document).ready(function(){
				$("div.postmsg").highlight("{{ highlight_word }}");
			});
		</script>
	{% endif %}
	{% block extra_meta %}{% endblock %}
</head>
<body>
    {% include 'djangobb_forum/header.html' %}

    {% block messages %}
        {% if messages %}
        <div id="messages" class="block">
            <h2><span>{% trans "Notice" %}</span></h2>
            <div class="box">
                <div class="inbox">
                    <ul class="messagelist">
                        {% for message in messages %}
                            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
        {% endif %}
    {% endblock messages %}
	{% block pre_content %}{% endblock %}
	{% block content %}{% endblock %}
	{% block post_content %}{% endblock %}
	<div id="brdfooter" class="block">
	<h2><span>{% trans "Board footer" %}</span></h2>
        <div class="box">
            <div class="inbox">
                {% block controls %}
                    <dl id="searchlinks" class="conl">
                        <dt><strong>{% trans "Search links" %}</strong></dt>
                        <dd><a href="{% url 'djangobb:search' %}?action=show_24h">{% trans "Show recent posts" %}</a></dd>
                        <dd><a href="{% url 'djangobb:search' %}?action=show_unanswered">{% trans "Show unanswered posts" %}</a></dd>
                        {% if user.is_authenticated %}
                        <dd><a href="{% url 'djangobb:search' %}?action=show_subscriptions">{% trans "Show your subscribed topics" %}</a></dd>
                        <dd>{% trans "Show your" %} <a href="{% url 'djangobb:search' %}?action=show_user&show_as=topics">{% trans "topics" %}</a>/<a href="{% url 'djangobb:search' %}?action=show_user&show_as=posts">{% trans "posts" %}</a></dd>
                        {% endif %}
                    </dl>
                {% endblock controls %}
                <p class="conr">На сайт <a href="{% url 'index' %}">obelektrike</a></p>
                <div class="clearer"></div>
                {% block lofi %}
                {% endblock lofi%}
            </div>
        </div>
    </div>
</div>
</div>
</body>
</html>

djangobb_forum/templates/djangobb_forum/header.html
{% load forum_extras %}
{% load i18n %}

<div id="djangobbwrap">
<div id="djangobbindex" class="djangobb">
<div id="brdheader" class="block">
	<div class="box">
		<div id="brdtitle" class="inbox">
			<h1><span><a href="{% url 'djangobb:index' %}">{{ forum_settings.HEADER|safe }}</a></span></h1>
			<p><span>{{ forum_settings.TAGLINE|safe }}</span></p>
		</div>
		<div id="brdmenu" class="inbox">
			<ul>
			{% block menu %}
				<li><a href="{% url 'index' %}">{% trans "На сайт obelektrike" %}</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</li>
				<li id="navindex"><a href="{% url 'djangobb:index' %}">{% trans "Index" %}</a></li>
				<li id="navuserlist"><a href="{% url 'djangobb:forum_users' %}">{% trans "User list" %}</a></li>
				<li id="navsearch"><a href="{% url 'djangobb:search' %}">{% trans "Search" %}</a></li>
				{% if user.is_superuser %}
					<li id="navadmin"><a href="{% url 'admin:index' %}">{% trans "Administration" %}</a></li>
				{% endif %}
				{% if user.is_authenticated %}
					<li id="navprofile"><a href="{% url 'djangobb:forum_profile' user.username %}">{% trans "Profile" %}</a></li>
					{% if forum_settings.PM_SUPPORT %}
						<li id="navpm"><a href="{% url 'messages_inbox' %}">{% trans "PM" %}</a></li> 
					{% endif %}
					<li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="{% url 'u-logout' %}?next={{request.path}}">{% trans "Выйти" %}</a></li>
				{% else %}
					<li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="{% url 'u-login' %}?next={{request.path}}">{% trans "Войти" %}</a></li>
					<li><a href="{% url 'u-registration' %}">{% trans "Регистрация" %}</a></li>
				{% endif %}
			{% endblock %}
			</ul>
		</div>
		<div id="brdwelcome" class="inbox">
			<ul class="conl">
				{% if user.is_authenticated %}
					<li>{% trans "Logged in as" %} <strong>{{ user.username }}</strong></li>
					<li>{% trans "Last visit:" %} {% forum_time user.last_login %}</li>
					{% if forum_settings.PM_SUPPORT and messages_inbox_count > 0 %}
						<ul><li class="pmlink"><strong><a href="{% url 'messages_inbox' %}">{% trans "There are new messages" %} ({{ messages_inbox_count }})</a></strong></li></ul>
					{% endif %}
				{% else %}
					<li>{% trans "You are not logged in." %}</li>
				{% endif %}
				{% if user.is_superuser and reports %}
					<li class="reportlink"><strong><a href="{% url 'admin:index' %}">{% trans "There are new reports" %} ({% new_reports %})</a></strong></li>
				{% endif %}
			</ul>
			{% if user.is_authenticated %}
				<ul class="conr">
					<li><a href="{% url 'djangobb:search' %}?action=show_new">{% trans "Show new posts since last visit" %}</a></li>
					<li><a href="{% url 'djangobb:misc' %}?action=markread">{% trans "Mark all topics as read" %}</a></li>
				</ul>
			{% endif %}
			<div class="clearer"></div>
		</div>
	</div>
</div>

{% if forum_settings.NOTICE %}
	<div id="announce" class="block">
		<h2><span>{% trans "Notice" %}</span></h2>
		<div class="box">
			<div class="inbox">
				<div>{{ forum_settings.NOTICE|safe }}</div>
			</div>
		</div>
	</div>
{% endif %}

djangobb_forum/templates/djangobb_forum/moderators.html
{% load forum_extras %}
{% load i18n %}
<em>({% trans "Moderated by" %}</em> 
	{% for moderator in moderators %}
		{% if forloop.last %}
			{{ moderator|profile_link }})
		{% else %}
			{{ moderator|profile_link }},
		{% endif %}
	{% endfor %}